### ISSUE TITLE
Separating Dataset and Pipeline configuration yaml files

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#11]
Separating the existing yaml configuration into two files to keep both logic separated and avoid any accidental changes to each other.

**Comment by Sohambutala** [comment]
Draft 1.0

---
active_recipe: standard # Selecting the recipe user wants to execute 
pipeline:
- recipe_name: standard # Name of the recipe which can be used for a recipe and decide which recipe needs to be executed by setting it in active_recipe.
  generateGrpah: false # To generate png of the DAG using networkx library
  stages: # Actual pipeline stages
  - stage: open_raw # name of the stage which will be the same as the prefect flow name
    saveOutput: true # Option to save the intermediate output, need to decide on the location of where to store the output or we can use the config from Dataset.yml
    parallelize: true # Option to parallelize the operation, most of the functions we have currently, we can decide on whether and how to parallelize or not. This option will be more useful for custom flows.
    externalParams: # To set external params. for example, bypassing some values or XML config files in scenarios of different sonar models.
      sonar_model: EK60
      xml_path: s3//
  - stage: update_platform
  - stage: compute_Sv
  - stage: add_lat_lon
  - stage: compute_MVBS
  - stage: bottom_detection
  - stage: apply_mask
  - stage: NASC

**Comment by leewujung** [comment]
Hey @Sohambutala , how about using [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) to show the above? It's kinda hard to read as a bullet list, and the indentation did not render correctly.

Also, I assume the above is a draft recipe for the pipeline without the dataset part? When you build it, it'll be great if you could incorporate the use of pydantic so that things can be checked automatically!

**Comment by Sohambutala** [comment]
Hi @leewujung, I have created pydantic classes for both and will add validations as required.
As of now, I haven't changed the dataset configuration part which is as below.

Dataset.yaml

```YAML
name: Bell_M._Shimada-SH1707-EK60
sonar_model: EK60
raw_regex: (.*)-?D(?P<date>\w{1,8})-T(?P<time>\w{1,6})
args:
  urlpath: s3://ncei-wcsd-archive/data/raw/{{ ship_name }}/{{ survey_name }}/{{ sonar_model }}/*.raw
  parameters:
    ship_name: Bell_M._Shimada
    survey_name: SH1707
    sonar_model: EK60
  storage_options:
    anon: true
  transect:
    file: ./x0007_fileset.txt
output:
  urlpath: ./combined_files
  overwrite: true
```

**Comment by Sohambutala** [comment]
Minor Update in pipeline config yaml structure. Made variable conforming to snake case and added name and module for importing the correct function in case of multiple implementations of a given function in different modules.

Will attempt to expose the predefined functions but module and name of function still would be relevant in case user wants to add their own logic.

Draft 1.1

```yaml
active_recipe: standard
pipeline:
- recipe_name: standard
  generate_grpah: false
  stages:
  - name: open_raw
    module: echoflow.stages_v2.subflows.open_raw
    save_output: true
    parallelize: true
    external_params:
      sonar_model: EK60
      xml_path: s3//
  - name: combine_echodata
    module: echoflow.stages_v2.subflows.combine_echodata
    save_output: true
    parallelize: true
    external_params:
      sonar_model: EK60
      xml_path: s3//
```
