### ISSUE TITLE
Dynamic Module Import and Function execution

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#15]
Module name and function which needs to be called need to be mentioned in the yaml file. For now, I am matching the names and executing the functions.
Below is the structure revised for the workaround.

```YAML
active_recipe: standard
pipeline:
- recipe_name: standard
  generateGrpah: false
  stages:
  - name: open_raw # Name of Function
    module: echoflow.stages_v2.Open_Raw # Module
    saveOutput: true
    parallelize: true
    externalParams:
      sonar_model: EK60
      xml_path: s3//
  - name: compute_Sv

```
